// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/external/weight': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/external/weight').default>>>>
    }
    '/api/user/login': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/user/login').default>>>>
    }
    '/api/user/register': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/user/register').default>>>>
    }
    '/api/weight': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/weight').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/nuxt/dist/core/runtime/nitro/handlers/renderer').default>>>>
    }
    '/__nuxt_island/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/#internal/nuxt/island-renderer').default>>>>
    }
  }
}
export {}