// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 2025/8/11 14:42:37
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["/Users/huxing/Documents/case/Siyou/github/nexus-of-notions/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/huxing/Documents/case/Siyou/github/nexus-of-notions/components/weight/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/huxing/Documents/case/Siyou/github/nexus-of-notions/components/exception/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/huxing/Documents/case/Siyou/github/nexus-of-notions/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/huxing/Documents/case/Siyou/github/nexus-of-notions/plugins/**/*.{js,ts,mjs}","/Users/huxing/Documents/case/Siyou/github/nexus-of-notions/composables/**/*.{js,ts,mjs}","/Users/huxing/Documents/case/Siyou/github/nexus-of-notions/utils/**/*.{js,ts,mjs}","/Users/huxing/Documents/case/Siyou/github/nexus-of-notions/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/huxing/Documents/case/Siyou/github/nexus-of-notions/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/huxing/Documents/case/Siyou/github/nexus-of-notions/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/huxing/Documents/case/Siyou/github/nexus-of-notions/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;